FROM registry.gitlab.com/kalilinux/build-scripts/kali-docker/kali

WORKDIR /root

RUN apt-get update \
  && apt-get install -y git stow zsh vim kali-linux-pwtools kali-linux-top10 kali-linux-web

RUN git clone https://github.com/mawalu/dotfiles.git \
  && git clone https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh \
  && cd dotfiles \
  && stow zsh vim \
  && vim +PlugInstall +qall \
  && chsh --shell /bin/zsh
