name: default
root: ~/
windows:
    - local:
        layout: 6eb3,211x55,0,0{105x55,0,0,0,105x55,106,0[105x27,106,0,1,105x27,106,28,2]}
        panes:
            - vim
            - clear
            - clear
    - remote:
        layout: eec0,211x55,0,0{105x55,0,0,3,105x55,106,0[105x27,106,0,4,105x27,106,28,5]}
        panes:
            - ssh user@h.alfa.mawalabs.de
            - clear
            - clear
    - work: 
        layout: 2c3e,211x55,0,0{105x55,0,0[105x48,0,0,6,105x6,0,49,9],105x55,106,0[105x27,106,0,7,105x27,106,28,8]}
        panes:
            - clear
            - cd ~/Documents/OpenVPN/arbeit/keys && clear
            - clear
            - clear
